sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t pdtejada/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dptejada/docker-react npm run test -- --coverage